---

### 1. 전처리 연습 (Tokenize, Cleansing&Normalization, Stemming&Lemmatization)

1. 데이터셋(corpus)을 찾는다. (만들어진 데이터셋, 크롤링, ...)
    - 🐿️ 이어지는 실습에 쓸 수 있을 법한 데이터 찾기 Tip
    - 여러 문장으로 이루어진 데이터셋이라면 일단 good
        - 리뷰 등 이어지지 않는 짧은 문장 여러 건 ok
        - 소설 등 이어지는 긴 문장 여러 건 ok
    - 대화형 데이터셋도 good
        - QnA로 구성되어 있는 corpus도 좋고
        - 일반적인 대화로 구성되어 있는 corpus도 좋아요~
    - 특정 도메인에 대한 정보를 담고 있는 데이터셋도 good
2. 전처리를 해본다.
    - 텍스트 자체를 깔끔하게 만드는 것까지만

---

---

---

### LG전자 공식 지식in QnA 200개 임시 전처리

In [21]:
import numpy as np
import pandas as pd

df = pd.read_json('../data/raw_data/kin.naver.com/lg_electronics_qna_200.json', encoding = 'utf-8')
df

,question,answer
0,업데이트 도중 제가 꺼버려서 그 뒤로 화면이 안켜져요 ㅠㅠ 이거는 무상수리가 가능한...,LG전자 고객도우미 입니다.​노트북 화면 관련으로 문의하신 내용 보았습니다.​업데이...
1,티비 모델명이 webOS TV LF6310 인데요넷플하고 다 되는데 티빙도 깔아지는...,"LG전자 고객도우미 입니다.​TV, 앱 이용시 화질 및 영화 재생이 되지 않아 문의..."
2,예전에는 괜찮았는데 lg gram 노트북을 사용한지 3년되었습니다.디자인과 학생이라...,LG전자 고객도우미 입니다.​​노트북 화면 색상 관련하여 문의하신 내용 보았습니다....
3,엘지 냉장고 야채칸 프레임 탈거 방법 문의드려요아래사진 상 빨간 부분을 탈거하려는데...,"LG전자 고객도우미 입니다.​냉장고, 야채칸 분리 관련으로 문의주신 내용 보았습니다..."
4,LG노트북을 사용하고 있습니다. 어젯만해도 잘됐습니다. 근대 오늘부터 노트북 부팅...,LG전자 고객도우미 입니다.​노트북 부팅 시 속도가 느리다는 문의 내용 보았습니다....
...,...,...
195,"Lg 그램을 사용하고 있는데요, 전부터 종종 네트워크 연결이 안 된다고 뜨길래 그때...",LG전자 고객도우미 입니다.​노트북 인터넷 연결이 안 된다는 문의 내용 보았습니다....
196,이번에 이사를 하면서 LG 16키로 건조기를 구입했는데요듀얼 인버터 히트펌프라고 하...,LG전자 고객도우미 입니다.​의류 건조기 사용 시 전기요금에 대해 문의주신 내용 보...
197,잘 사용하고 있었는데 어느 순간부터 이런게 뜨네요ㅜㅜ 해결 방법좀 알려주세요 ㅜㅜㅜ...,LG전자 고객도우미 입니다.​노트북 부팅 관련으로 문의하신 내용 보았습니다.​첨부해...
198,건조기 표준코스가 송풍으로 설정되어 있습니다.다른 코스로 바꿔봐도 송풍입니다.사용중...,LG전자 고객도우미 입니다.​건조 진행 상태 안내 아이콘에 대해 문의주신 내용 보았...
199,제가 이틀전에 윈도우 11로 업데이트를 했는데 노트북 저장공간이 8기가빼고 싹다 채...,LG전자 고객도우미 입니다.​윈도우즈 11로 업그레이드 후 저장 공간 관련으로 문의...

---

##### Step 1. 텍스트 정규화 (Text Normalization)

(1) 영어 문자 대문자 변환 >>> 대문자로 변환 (LG 상호도 대문자고 대개 제품코드는 대문자로 표기되므로)

In [22]:
df1 = df.applymap(str.upper)

C:\Users\jinsa\AppData\Local\Temp\ipykernel_29000\2195754351.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1 = df.applymap(str.upper)

(2) 불필요한 문자 제거 / 변환 + 띄어쓰기 적용

In [23]:
import re

def cleansing(text):
    # 특수문자 & 노이즈 제거 (ㅠㅠ, ㅋㅋ 등도 제거)
    text = re.sub(r'[^가-힣a-zA-Z0-9\s\.\?\!]', '', text)
    
    # 연속 공백을 하나의 공백으로
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df1['question'] = df1['question'].apply(cleansing)
df1['answer'] = df1['answer'].apply(cleansing)

df1

,question,answer
0,업데이트 도중 제가 꺼버려서 그 뒤로 화면이 안켜져요 이거는 무상수리가 가능한건가요?,LG전자 고객도우미 입니다.노트북 화면 관련으로 문의하신 내용 보았습니다.업데이트 ...
1,티비 모델명이 WEBOS TV LF6310 인데요넷플하고 다 되는데 티빙도 깔아지는...,LG전자 고객도우미 입니다.TV 앱 이용시 화질 및 영화 재생이 되지 않아 문의주신...
2,예전에는 괜찮았는데 LG GRAM 노트북을 사용한지 3년되었습니다.디자인과 학생이라...,LG전자 고객도우미 입니다.노트북 화면 색상 관련하여 문의하신 내용 보았습니다.아래...
3,엘지 냉장고 야채칸 프레임 탈거 방법 문의드려요아래사진 상 빨간 부분을 탈거하려는데...,LG전자 고객도우미 입니다.냉장고 야채칸 분리 관련으로 문의주신 내용 보았습니다. ...
4,LG노트북을 사용하고 있습니다. 어젯만해도 잘됐습니다. 근대 오늘부터 노트북 부팅속...,LG전자 고객도우미 입니다.노트북 부팅 시 속도가 느리다는 문의 내용 보았습니다.문...
...,...,...
195,LG 그램을 사용하고 있는데요 전부터 종종 네트워크 연결이 안 된다고 뜨길래 그때마...,LG전자 고객도우미 입니다.노트북 인터넷 연결이 안 된다는 문의 내용 보았습니다.아...
196,이번에 이사를 하면서 LG 16키로 건조기를 구입했는데요듀얼 인버터 히트펌프라고 하...,LG전자 고객도우미 입니다.의류 건조기 사용 시 전기요금에 대해 문의주신 내용 보았...
197,잘 사용하고 있었는데 어느 순간부터 이런게 뜨네요 해결 방법좀 알려주세요 최대한 빠...,LG전자 고객도우미 입니다.노트북 부팅 관련으로 문의하신 내용 보았습니다.첨부해 주...
198,건조기 표준코스가 송풍으로 설정되어 있습니다.다른 코스로 바꿔봐도 송풍입니다.사용중...,LG전자 고객도우미 입니다.건조 진행 상태 안내 아이콘에 대해 문의주신 내용 보았습...
199,제가 이틀전에 윈도우 11로 업데이트를 했는데 노트북 저장공간이 8기가빼고 싹다 채...,LG전자 고객도우미 입니다.윈도우즈 11로 업그레이드 후 저장 공간 관련으로 문의하...

In [24]:
# 한글 띄어쓰기 해주는 PyKoSpacing 패키지 설치 (데이터 중간 중간 띄어쓰기가 안 되어있는 경우가 존재)

# !pip install git+https://github.com/haven-jeon/PyKoSpacing.git

In [25]:
# 띄어쓰기 적용하려 했는데, 생각보다 question에서의 띄어쓰기 결과값이 좋아보이지는 않음 (보류)

# from pykospacing import Spacing

# spacing = Spacing()

# def pkspacing(text):
#     # Pykospacing을 통한 띄어쓰기 적용
#     text = spacing(text)
#     return text

# df['question'] = df['question'].apply(pkspacing)
# df['answer'] = df['answer'].apply(pkspacing)

# df

In [26]:
# # 답변의 인삿말 제거
# df1['answer'] = df1['answer'].str.split('내용 보았습니다').str[1]

# # 답변의 메크로식 안내문 부분 제거 (답변 맨 뒷부분)
# df1['answer'] = df1['answer'].str.split('감사합니다.').str[0]

# # ################################################################

# # **문제 발생!!!**

# df1.info()      # 해당 전처리 후, df1 answer 행이 빈 경우가 다수(200건 중 13건) 발견됨.

# print('=' * 80)

# print(df1[df1.isnull()['answer']==True])

# print('=' * 80)

# print(df.iloc[45])      # 전처리(인삿말과 메크로 마무리 제거) 전에는 멀쩡히 답변이 존재했었음

# print('=' * 80)

# print(df[df['answer'].str.contains('보았습니다')==False])    # 원본 데이터를 보니, '내용 보았습니다'라고 적지 않은 케이스가 다수 존재했었던 것.
#                                                             # 그럼 '보았습니다'만 제거하려 하는데, 없는 경우도 있을까? >>> 3건 있음

# print('=' * 80)

# # 인삿말에 '보았습니다'가 없는 경우, '감사합니다'가 모두 앞에 나와서 메크로 답변 처리할 때도 애를 먹을 것이 분명하다. >>> 3건은 포기 
# print(df.loc[47, 'answer'])
# print(df.loc[52, 'answer'])
# print(df.loc[54, 'answer'])

In [27]:
# 답변의 인삿말 제거(수정 ver.)
df1['answer'] = df1['answer'].str.split('보았습니다.').str[1].str.strip()

# 답변의 메크로식 안내문 부분 제거 (답변 맨 뒷부분)
df1['answer'] = df1['answer'].str.split('감사합니다.').str[0].str.strip()

# 혹시나 해서 question도 strip하기
df1['question'] = df1['question'].str.strip()

df1.info()          # 3건만 결측치 발생

df1 = df1.dropna(how='any').reset_index(drop=True)

df1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  200 non-null    object
 1   answer    197 non-null    object
dtypes: object(2)
memory usage: 3.3+ KB

,question,answer
0,업데이트 도중 제가 꺼버려서 그 뒤로 화면이 안켜져요 이거는 무상수리가 가능한건가요?,업데이트 중 비정상 종료가 되어 나오는 증상 일 수 있습니다.충전이 되었다면 어댑터...
1,티비 모델명이 WEBOS TV LF6310 인데요넷플하고 다 되는데 티빙도 깔아지는...,해당 증상은 WEBOS 2.0 플렛폼에서 일부 영화 컨텐츠 재생이 불가하여컨텐츠사로...
2,예전에는 괜찮았는데 LG GRAM 노트북을 사용한지 3년되었습니다.디자인과 학생이라...,아래 내용대로 그래픽 드라이버 제거 후 재설치 해보시기 바랍니다.1. 시작 버튼에서...
3,엘지 냉장고 야채칸 프레임 탈거 방법 문의드려요아래사진 상 빨간 부분을 탈거하려는데...,첨부해주신 사진 확인시 표시 부분이 전체로 분리되는 것으로 보여집니다. 다만 테두리...
4,LG노트북을 사용하고 있습니다. 어젯만해도 잘됐습니다. 근대 오늘부터 노트북 부팅속...,문의주신 현상은 시작프로그램의 영향 또는 바이러스에 감염되거나 악성코드가 있는 경우...
...,...,...
192,LG 그램을 사용하고 있는데요 전부터 종종 네트워크 연결이 안 된다고 뜨길래 그때마...,아래와 같이 진행해 주시기 바랍니다. 무선 연결1. 키보드 FNF6을 눌러 비행기 ...
193,이번에 이사를 하면서 LG 16키로 건조기를 구입했는데요듀얼 인버터 히트펌프라고 하...,모델에 따른 소비전력 및 사용 패턴주로 건조하는 빨래감의 종류 및 양 등과 댁내 기...
194,잘 사용하고 있었는데 어느 순간부터 이런게 뜨네요 해결 방법좀 알려주세요 최대한 빠...,첨부해 주신 사진처럼 BOOT MENU APP MENU가 나온다면바이오스가 잘못 설...
195,건조기 표준코스가 송풍으로 설정되어 있습니다.다른 코스로 바꿔봐도 송풍입니다.사용중...,첨부해 주신 사진 확인 시 송풍이 아닌 표준으로 설정된 상태입니다.건조 후 옷감의 ...
196,제가 이틀전에 윈도우 11로 업데이트를 했는데 노트북 저장공간이 8기가빼고 싹다 채...,업그레이드 파일이 아닌 다른 파일이 생성되었는지 등 확인을 위해전문 엔지니어가 전반...

In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  197 non-null    object
 1   answer    197 non-null    object
dtypes: object(2)
memory usage: 3.2+ KB

In [29]:
# 파일로 저장하고 봤는데, 운이 좋게도 질문 자체가 비어있는 경우가 존재했음. >>> 원본 데이터에도 질문 부분이 ""로만 되어있음.
# 실제 데이터를 확인해보진 않았지만, 질문 내용에 사진만 올린 게 아닐까 사료됨. >>> 검증해야할 부분이긴 함

print(df1.iloc[50])

print(df1.iloc[50].isnull())
# 이런 경우는 isnull()로 걸러지지 않음. 빈 문자열인 거지 결측치는 아니기 때문.

# 그래서 이런 경우는, 다음과 같이 처리해야한다.
df1.replace({'question':""}, np.nan, inplace=True)
        # df1['question'].replace("", np.nan, inplace=True)
        # 위와 같이 썼을 때에는 다음과 같은 Warning이 떴는데, 핵심은 마지막 줄처럼 쓰라는 의미였다.
            # FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
            # The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.
            # For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

# df1.isnull().sum()    # 정상적으로 빈 문자열은 결측치로 전환하였음

df1 = df1.dropna(how = 'any').reset_index(drop=True)

df1.info()

question
answer      실내기 또는 실외기의 이상이 감지되면 숫자 및 LED 램프가 깜박거립니다. 문의주신...
Name: 50, dtype: object
question    False
answer      False
Name: 50, dtype: bool
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  196 non-null    object
 1   answer    196 non-null    object
dtypes: object(2)
memory usage: 3.2+ KB

In [30]:
df1.to_csv('../data/preprocessed_data/kin.naver.com/preprocessing_200data_step1.csv', encoding = 'utf-8', index = False)

---

##### Step 2. 토큰화 (문장 단위 토큰화)
- 챗봇을 만든다고 가정했을 때에는 문장 단위로 나누는 것이 좋아보임

In [31]:
import kss

# df2 = pd.read_csv('../data/preprocessed_data/kin.naver.com/preprocessing_200data_step1.csv', encoding = 'utf-8')

# df2['question'] = df2['question'].apply(kss.split_sentences)
# df2['answer'] = df2['answer'].apply(kss.split_sentences)

In [32]:
# df2.to_csv('../data/raw_data/milestones/kin.naver.com_step2_milestone.csv', encoding = 'utf-8', index = False)
    # 전반적으로 문장 토큰화가 잘 된 것 같음

In [ ]:
# 위에서 하지 못한 전처리가 하나 존재
# 답변을 보면 링크로 대체한 경우가 종종 존재하는데, 링크 참고해주세요~ 하는 문장들의 세부 표현이 다 다른 듯하다.
# 그래서 '답변'을 문장 토큰화한 후, 각 문장 토큰 list 중에서 링크라는 단어를 포함한 요소부터 그 이후 것들을 다 제거하는 방식으로 하려 했음.

import ast

df2_5 = pd.read_csv('../data/raw_data/milestones/kin.naver.com_step2_milestone.csv', encoding = 'utf-8')

df2_5['answer'] = df2_5['answer'].apply(ast.literal_eval)   # read_csv로 불러왔기에 자료형이 string꼴이 됨. >>> list 형태로 다시 복구해야...
                                                            # KSS로 토큰화한 걸 그대로 사용했다면 이런 작업은 필요 없었겠죠...

def finding_useless(a_list):
    get_rid_of = ['링크', 'HTTPS', 'WWW']

    for index, factor in enumerate(a_list):
        if any(word in factor for word in get_rid_of):
            return a_list[:index]    

    return a_list

df2_5['answer'] = df2_5['answer'].apply(finding_useless)

# df2_5.to_csv('../data/raw_data/milestones/kin.naver.com_step2_5_milestone.csv', encoding = 'utf-8', index = False)

In [38]:
# 위에 코드를 돌리니 또 보이는 문제가 발생.
# 이후 궁금한 점이 있으면 고객 상담실로 연락 달라는 문구가 있는 답변들이 다수 존재 >>> 불필요할 듯
# 다만 가끔 고객상담실이라 적을 때도 있고 고객 상담실이라 적을 때도 있음. >>> 크롤링할 때 LG 답변만을 골랐던 방식을 채용하면 될 듯.

def finding_cs(a_list):
    for index, factor in enumerate(a_list):
        if '고객상담실' in factor.replace(' ',''):
            return a_list[:index]    

    return a_list

df2_5['answer'] = df2_5['answer'].apply(finding_cs)

df2_5.to_csv('../data/preprocessed_data/kin.naver.com/preprocessing_200data_step2.csv', encoding = 'utf-8', index = False)

---

### 진행하진 못했지만 고려할만한 부분
- finding_useless 함수에서 HTTP를 제거한 것은 좋은데,,, 
    - 'HTTP 링크의 제목' 'HTTP~' 이렇게 되있는 상태에서 제목은 제거되지 않고, 순수 링크만 제거된 경우 포착... >>> 시간 있으면 보완합시다..
- 마지막 csv를 보면 문장이 잘 나누어지지 못한 게 좀 많음
    > 위에서 성능이 좋지 못했던 PyKoSpacing을 다시 적용하면 어떨지? 데이터도 많이 정제됐으니, 성능에 변화가 있을 수도...  
    > 제대로 나누어졌다면 다시 KSS 토큰화를 진행해보면 좋을 듯
- 질문 중에 모델명을 텍스트로 적지 않고 사진 등으로 대체한 경우가 종종 있는 거 같은데... 이건 진짜 답이 없네... 아이고 아이고...