---

### 1. 전처리 연습 (Tokenize, Cleansing&Normalization, Stemming&Lemmatization)

1. 데이터셋(corpus)을 찾는다. (만들어진 데이터셋, 크롤링, ...)
    - 🐿️ 이어지는 실습에 쓸 수 있을 법한 데이터 찾기 Tip
    - 여러 문장으로 이루어진 데이터셋이라면 일단 good
        - 리뷰 등 이어지지 않는 짧은 문장 여러 건 ok
        - 소설 등 이어지는 긴 문장 여러 건 ok
    - 대화형 데이터셋도 good
        - QnA로 구성되어 있는 corpus도 좋고
        - 일반적인 대화로 구성되어 있는 corpus도 좋아요~
    - 특정 도메인에 대한 정보를 담고 있는 데이터셋도 good
2. 전처리를 해본다.
    - 텍스트 자체를 깔끔하게 만드는 것까지만

---

### LG전자 공식 지식in QnA 200개 임시 전처리

In [15]:
import numpy as np
import pandas as pd

df = pd.read_json('../raw_data/kin.naver.com/lg_electronics_qna_200.json', encoding = 'utf-8')
df

,question,answer
0,업데이트 도중 제가 꺼버려서 그 뒤로 화면이 안켜져요 ㅠㅠ 이거는 무상수리가 가능한...,LG전자 고객도우미 입니다.​노트북 화면 관련으로 문의하신 내용 보았습니다.​업데이...
1,티비 모델명이 webOS TV LF6310 인데요넷플하고 다 되는데 티빙도 깔아지는...,"LG전자 고객도우미 입니다.​TV, 앱 이용시 화질 및 영화 재생이 되지 않아 문의..."
2,예전에는 괜찮았는데 lg gram 노트북을 사용한지 3년되었습니다.디자인과 학생이라...,LG전자 고객도우미 입니다.​​노트북 화면 색상 관련하여 문의하신 내용 보았습니다....
3,엘지 냉장고 야채칸 프레임 탈거 방법 문의드려요아래사진 상 빨간 부분을 탈거하려는데...,"LG전자 고객도우미 입니다.​냉장고, 야채칸 분리 관련으로 문의주신 내용 보았습니다..."
4,LG노트북을 사용하고 있습니다. 어젯만해도 잘됐습니다. 근대 오늘부터 노트북 부팅...,LG전자 고객도우미 입니다.​노트북 부팅 시 속도가 느리다는 문의 내용 보았습니다....
...,...,...
195,"Lg 그램을 사용하고 있는데요, 전부터 종종 네트워크 연결이 안 된다고 뜨길래 그때...",LG전자 고객도우미 입니다.​노트북 인터넷 연결이 안 된다는 문의 내용 보았습니다....
196,이번에 이사를 하면서 LG 16키로 건조기를 구입했는데요듀얼 인버터 히트펌프라고 하...,LG전자 고객도우미 입니다.​의류 건조기 사용 시 전기요금에 대해 문의주신 내용 보...
197,잘 사용하고 있었는데 어느 순간부터 이런게 뜨네요ㅜㅜ 해결 방법좀 알려주세요 ㅜㅜㅜ...,LG전자 고객도우미 입니다.​노트북 부팅 관련으로 문의하신 내용 보았습니다.​첨부해...
198,건조기 표준코스가 송풍으로 설정되어 있습니다.다른 코스로 바꿔봐도 송풍입니다.사용중...,LG전자 고객도우미 입니다.​건조 진행 상태 안내 아이콘에 대해 문의주신 내용 보았...
199,제가 이틀전에 윈도우 11로 업데이트를 했는데 노트북 저장공간이 8기가빼고 싹다 채...,LG전자 고객도우미 입니다.​윈도우즈 11로 업그레이드 후 저장 공간 관련으로 문의...

##### Step 1. 텍스트 정규화 (Text Normalization)

(1) 영어 문자 대문자 변환 >>> 대문자로 변환 (LG 상호도 대문자고 대개 제품코드는 대문자로 표기되므로)

In [16]:
df = df.applymap(str.upper)

C:\Users\jinsa\AppData\Local\Temp\ipykernel_22280\1400984656.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(str.upper)

(2) 불필요한 문자 제거 / 변환 + 띄어쓰기 적용

In [17]:
# 한글 띄어쓰기 해주는 PyKoSpacing 패키지 설치 (데이터 중간 중간 띄어쓰기가 안 되어있는 경우가 존재)

# !pip install git+https://github.com/haven-jeon/PyKoSpacing.git

In [18]:
import re

def cleansing(text):
    # 특수문자 & 노이즈 제거 (ㅠㅠ, ㅋㅋ 등도 제거)
    text = re.sub(r'[^가-힣a-zA-Z0-9\s\.\?\!]', '', text)
    
    # 연속 공백을 하나의 공백으로
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df['question'] = df['question'].apply(cleansing)
df['answer'] = df['answer'].apply(cleansing)

df

,question,answer
0,업데이트 도중 제가 꺼버려서 그 뒤로 화면이 안켜져요 이거는 무상수리가 가능한건가요?,LG전자 고객도우미 입니다.노트북 화면 관련으로 문의하신 내용 보았습니다.업데이트 ...
1,티비 모델명이 WEBOS TV LF6310 인데요넷플하고 다 되는데 티빙도 깔아지는...,LG전자 고객도우미 입니다.TV 앱 이용시 화질 및 영화 재생이 되지 않아 문의주신...
2,예전에는 괜찮았는데 LG GRAM 노트북을 사용한지 3년되었습니다.디자인과 학생이라...,LG전자 고객도우미 입니다.노트북 화면 색상 관련하여 문의하신 내용 보았습니다.아래...
3,엘지 냉장고 야채칸 프레임 탈거 방법 문의드려요아래사진 상 빨간 부분을 탈거하려는데...,LG전자 고객도우미 입니다.냉장고 야채칸 분리 관련으로 문의주신 내용 보았습니다. ...
4,LG노트북을 사용하고 있습니다. 어젯만해도 잘됐습니다. 근대 오늘부터 노트북 부팅속...,LG전자 고객도우미 입니다.노트북 부팅 시 속도가 느리다는 문의 내용 보았습니다.문...
...,...,...
195,LG 그램을 사용하고 있는데요 전부터 종종 네트워크 연결이 안 된다고 뜨길래 그때마...,LG전자 고객도우미 입니다.노트북 인터넷 연결이 안 된다는 문의 내용 보았습니다.아...
196,이번에 이사를 하면서 LG 16키로 건조기를 구입했는데요듀얼 인버터 히트펌프라고 하...,LG전자 고객도우미 입니다.의류 건조기 사용 시 전기요금에 대해 문의주신 내용 보았...
197,잘 사용하고 있었는데 어느 순간부터 이런게 뜨네요 해결 방법좀 알려주세요 최대한 빠...,LG전자 고객도우미 입니다.노트북 부팅 관련으로 문의하신 내용 보았습니다.첨부해 주...
198,건조기 표준코스가 송풍으로 설정되어 있습니다.다른 코스로 바꿔봐도 송풍입니다.사용중...,LG전자 고객도우미 입니다.건조 진행 상태 안내 아이콘에 대해 문의주신 내용 보았습...
199,제가 이틀전에 윈도우 11로 업데이트를 했는데 노트북 저장공간이 8기가빼고 싹다 채...,LG전자 고객도우미 입니다.윈도우즈 11로 업그레이드 후 저장 공간 관련으로 문의하...

In [19]:
# 띄어쓰기 적용하려 했는데, 생각보다 question에서의 띄어쓰기 결과값이 좋아보이지는 않음 (보류)

# from pykospacing import Spacing

# spacing = Spacing()

# def pkspacing(text):
#     # Pykospacing을 통한 띄어쓰기 적용
#     text = spacing(text)
#     return text

# df['question'] = df['question'].apply(pkspacing)
# df['answer'] = df['answer'].apply(pkspacing)

# df

In [ ]:
# 답변의 인삿말 제거
df['answer'] = df['answer'].str.split('내용 보았습니다.').str[1]

# 답변의 메크로식 안내문 부분 제거 (답변 맨 뒷부분)
df['answer'] = df['answer'].str.split('감사합니다.').str[0]

In [ ]:
# df.to_csv('./testing.csv', index=False, encoding='utf-8')

##### Step 2. 토큰화 (문장)